### ISSUE TITLE
Base64 PDF File print

### ISSUE THREAD

**Issue by rdgoutiyama** [micwallace/WebPrint#11]
How I can print pdf file base64 encoded ?

When I send encoded base64 pdf file, the thermal printer print cannot print the content.
Prints the base64 string decoded.

Thanks.

**Comment by micwallace** [comment]
Most thermal printers only support certain formats, the most common is ESCP. You can't just send a PDF to the printer and expect it to print correctly. You need to convert whatever you want to print into a language the printer understands. Otherwise the printer will just print in line/text mode.

Cheers,
Michael

On 28 April 2018 5:16:12 AM AEST, rdgoutiyama <notifications@github.com> wrote:
>How I can print pdf file base64 encoded ?
>
>When I send encoded base64 pdf file, the thermal printer print cannot
>print the content.
>Prints the base64 string decoded.
>
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/WebPrint/issues/11

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rdgoutiyama** [comment]
Okay,

Thank you
