### ISSUE TITLE
Print from url/html page to network printer

### ISSUE THREAD

**Issue by vijaythecoder** [micwallace/WebPrint#8]
I am looking for solution that can print the webpage to kitchen printer(network) and another webpage to receipt printer (network or USB). I think I can dynamically send the necessary data to respective printers, but is there a way to print from html page? 

when I inspected the source code 

```
this.printHtml = function (data, printer) {
        alert(data)
        if (isAndroid){
            alert("HTML printing is not available in Android.");
            return;
        }
        var request = {a: "printhtml", printer: printer, data: data};
        sendAppletRequest(request);
    };
```

but how do I pass it as network printer ? I tried modifying it to send options as 
`var request = {a: "printhtml", socket: printer, data: data};` with `printer` as `ip:port` but the printer doesn't respond. Thanks once again for the great package

**Comment by tresf** [comment]
> @tresf I am totally stuck on this( #8 ) for more than 8 hours and found no solution #8 could you help me this out please?

I'm sorry, I was only chiming in at #7 because the solution crossed paths.  This product is a fork of another one, I manage the other one, so I'm not familiar with the library.  @micwallace would have to assist, sorry I cannot be of more help.

**Comment by vijaythecoder** [comment]
@tresf you mean qz worked for you? it is too costly to use in commercial products. if its not qz, can you help me with the name? Thanks for your replies

**Comment by tresf** [comment]
> @tresf you mean qz worked for you? it is too costly to use in commercial products. if its not qz, can you help me with the name? Thanks for your replies

Out of respect to @micwallace, I've emailed you separately.

**Comment by micwallace** [comment]
Hi,

Unfortuantely printing HTML directly to a network printer is not supported. This is because the printer driver handles the conversion of HTML into a format the printer understands (postscript, PCL, ESCP, etc). As a workaround you can install the printer onto the computer as a network printer and use the code above to print html.

Or if you want to go the hard route like I did, you can render the HTML into an ESCP bitmap and send it directly to a receipt printer on the network. For an example of how to do this, see my POS project: https://github.com/micwallace/wallacepos/blob/master/assets/js/wpos/print.js
